#!/usr/bin/env python3


import argparse
import configparser
from trello import TrelloClient



def main():
    
    args = parse_arguments()

    config = configparser.ConfigParser()
    config.readfp(open(args.conf))

    client = setup_trello_client(config)

    print(dir(client))
    print(client.list_boards())

    # TODO next: Investigate why autoamtic token authorization isn't going through
    # Can I get it through interactively?


def setup_trello_client(conf):

    api_key = conf.get('tokens', 'api_key')
    api_secret = conf.get('tokens', 'api_secret')
    token_key = conf.get('tokens', 'token_key')
    token_secret = conf.get('tokens', 'token_secret')

    client = TrelloClient(
        api_key=api_key,
        api_secret=api_secret,
        token=token_key,
        token_secret=token_secret
    )
    
    return client


def parse_arguments():

    parser = argparse.ArgumentParser()
    parser.add_argument('--conf', required=True)
    args = parser.parse_args()
    return args


if __name__ == '__main__':
    main()
